@extends('layouts.app')

@section('title', 'Conteos físicos')
@section('page-title', 'Conteos físicos')
@section('page-subtitle', 'Compara lo encontrado en bodega con el sistema sin alterar saldos silenciosamente.')
@section('header-actions')<a href="{{ route('inventory-counts.create') }}" class="btn-primary">＋ Nuevo conteo</a>@endsection

@section('content')
    <div class="space-y-6"><nav class="flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('inventory.index') }}">Existencias</a><a class="btn-secondary" href="{{ route('inventory-documents.index') }}">Entradas y ajustes</a><a class="btn-secondary border-leaf-600 text-leaf-700" href="{{ route('inventory-counts.index') }}">Conteos</a><a class="btn-secondary" href="{{ route('inventory-movements.index') }}">Bitácora</a></nav><section class="card p-5"><form method="GET" class="grid gap-4 sm:grid-cols-3"><div><label class="form-label">Bodega</label><select class="form-input" name="warehouse_id"><option value="">Todas</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(request('warehouse_id') === $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></div><div><label class="form-label">Estado</label><select class="form-input" name="status"><option value="">Todos</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="flex items-end gap-2"><button class="btn-primary flex-1">Filtrar</button><a class="btn-secondary" href="{{ route('inventory-counts.index') }}">Limpiar</a></div></form></section><section class="card overflow-hidden">@if($counts->isEmpty())<div class="p-6"><x-empty-state title="Sin conteos" description="Inicia un conteo físico para verificar toda la bodega."><x-slot:action><a class="btn-primary" href="{{ route('inventory-counts.create') }}">Iniciar conteo</a></x-slot:action></x-empty-state></div>@else<div class="overflow-x-auto"><table class="w-full min-w-[800px]"><thead class="bg-stone-50"><tr><th class="table-heading">Conteo</th><th class="table-heading">Bodega</th><th class="table-heading">Responsable</th><th class="table-heading">Avance</th><th class="table-heading">Estado</th></tr></thead><tbody>@foreach($counts as $count)<tr><td class="table-cell"><a class="font-bold text-leaf-700 hover:underline" href="{{ route('inventory-counts.show', $count) }}">{{ $count->count_number }}</a><p class="text-xs text-ink-600">{{ $count->counted_on->format('d/m/Y') }}</p></td><td class="table-cell">{{ $count->warehouse->name }}</td><td class="table-cell">{{ $count->creator->name }}</td><td class="table-cell"><p class="font-semibold">{{ $count->counted_items_count }} / {{ $count->items_count }}</p><div class="mt-1 h-1.5 w-32 overflow-hidden rounded-full bg-stone-200"><div class="h-full bg-leaf-600" style="width: {{ $count->items_count ? min(100, ($count->counted_items_count / $count->items_count) * 100) : 0 }}%"></div></div></td><td class="table-cell"><x-inventory-status-badge :status="$count->status" /></td></tr>@endforeach</tbody></table></div><div class="border-t border-stone-100 px-5 py-4">{{ $counts->links() }}</div>@endif</section></div>
@endsection
