@extends('layouts.app')

@section('title', $count->count_number)
@section('page-title', $count->count_number)
@section('page-subtitle', $count->warehouse->name.' · '.$count->counted_on->format('d/m/Y'))
@section('header-actions')<a href="{{ route('inventory-counts.index') }}" class="btn-secondary">Volver</a>@endsection

@section('content')
    @php($completed = $count->items->whereNotNull('counted_quantity')->count())
    <div class="space-y-6"><section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Estado</p><div class="mt-3"><x-inventory-status-badge :status="$count->status" /></div></article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Avance</p><p class="mt-2 text-3xl font-black">{{ $completed }} / {{ $count->items->count() }}</p></article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Bodega</p><p class="mt-2 font-bold">{{ $count->warehouse->name }}</p><p class="text-xs text-ink-600">{{ $count->warehouse->code }}</p></article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Responsable</p><p class="mt-2 font-bold">{{ $count->creator->name }}</p><p class="text-xs text-ink-600">{{ $count->created_at->format('d/m/Y H:i') }}</p></article></section>

        @if($count->status === \App\InventoryCountStatus::Cancelled)<section class="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><p class="font-bold">Conteo cancelado</p><p class="mt-1 text-sm">{{ $count->cancellation_reason }}</p></section>@endif

        @if($count->isDraft())<div class="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm leading-6 text-sky-950"><strong>Conteo ciego:</strong> las cantidades del sistema permanecen ocultas mientras cuentas para reducir sesgos. Se mostrarán junto con las diferencias después de aplicar.</div>@endif

        <form method="POST" action="{{ route('inventory-counts.update', $count) }}">@csrf @method('PUT')<section class="card overflow-hidden"><div class="border-b border-stone-100 px-5 py-4"><h2 class="font-bold">Productos a contar</h2><p class="text-sm text-ink-600">Registra cero cuando hayas revisado un producto y no exista físicamente.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[800px]"><thead class="bg-stone-50"><tr><th class="table-heading">Producto</th>@unless($count->isDraft())<th class="table-heading text-right">Sistema</th>@endunless<th class="table-heading text-right">Conteo físico</th>@unless($count->isDraft())<th class="table-heading text-right">Diferencia</th>@endunless<th class="table-heading">Observación</th></tr></thead><tbody>@foreach($count->items as $index => $item)<tr><td class="table-cell"><p class="font-semibold">{{ $item->product_name }}</p><p class="text-xs text-ink-600">{{ $item->product_sku }} · {{ $item->base_unit_symbol }}</p><input type="hidden" name="items[{{ $index }}][id]" value="{{ $item->id }}"></td>@unless($count->isDraft())<td class="table-cell text-right">{{ rtrim(rtrim($item->expected_quantity, '0'), '.') }}</td>@endunless<td class="table-cell text-right">@if($count->isDraft())<input class="form-input ml-auto w-40 text-right" name="items[{{ $index }}][counted_quantity]" type="number" min="0" step="0.000001" value="{{ $item->counted_quantity }}" placeholder="Pendiente">@else<span class="font-bold">{{ rtrim(rtrim($item->counted_quantity, '0'), '.') }}</span>@endif</td>@unless($count->isDraft())<td class="table-cell text-right font-black {{ bccomp($item->difference, '0', 6) < 0 ? 'text-red-700' : (bccomp($item->difference, '0', 6) > 0 ? 'text-emerald-700' : '') }}">{{ bccomp($item->difference, '0', 6) > 0 ? '+' : '' }}{{ rtrim(rtrim($item->difference, '0'), '.') }}</td>@endunless<td class="table-cell">@if($count->isDraft())<input class="form-input" name="items[{{ $index }}][notes]" maxlength="500" value="{{ $item->notes }}" placeholder="Opcional">@else{{ $item->notes ?: '—' }}@endif</td></tr>@endforeach</tbody></table></div>@if($count->isDraft())<div class="flex justify-end border-t border-stone-100 p-5"><button class="btn-primary">Guardar avance</button></div>@endif</section></form>

        @if($count->isDraft())<section class="grid items-start gap-6 lg:grid-cols-2"><div class="card p-5"><h2 class="font-bold">Aplicar conteo</h2><p class="mt-2 text-sm leading-6 text-ink-600">Todos los productos deben estar contados. Las diferencias generarán movimientos auditables; las reservas de pedidos no se eliminan.</p><form method="POST" action="{{ route('inventory-counts.post', $count) }}" class="mt-4" data-confirm="¿Aplicar este conteo y ajustar la existencia física?">@csrf<button class="btn-primary w-full" @disabled($completed !== $count->items->count())>Aplicar diferencias</button></form></div><div class="card border-red-200 p-5"><h2 class="font-bold text-red-800">Cancelar conteo</h2><p class="mt-2 text-sm text-ink-600">No modificará ninguna existencia.</p><form method="POST" action="{{ route('inventory-counts.cancel', $count) }}" class="mt-4 space-y-3" data-confirm="¿Cancelar este conteo?">@csrf<label class="form-label">Motivo *</label><textarea class="form-input min-h-20" name="reason" required maxlength="1000"></textarea><button class="btn-danger w-full">Cancelar conteo</button></form></div></section>@endif

        @if($count->notes)<section class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Notas</p><p class="mt-2 whitespace-pre-line text-sm">{{ $count->notes }}</p></section>@endif
    </div>
@endsection
