@extends('layouts.app')

@php($editing = $inventoryDocument->exists)
@section('title', $editing ? 'Editar movimiento' : 'Nuevo movimiento')
@section('page-title', $editing ? 'Editar movimiento' : 'Nuevo movimiento')
@section('page-subtitle', 'El documento permanecerá en borrador hasta que revises y apliques sus líneas.')
@section('header-actions')<a href="{{ $editing ? route('inventory-documents.show', $inventoryDocument) : route('inventory-documents.index') }}" class="btn-secondary">Volver</a>@endsection

@section('content')
    <form method="POST" action="{{ $editing ? route('inventory-documents.update', $inventoryDocument) : route('inventory-documents.store') }}" class="space-y-6">@csrf @if($editing)@method('PUT')@endif
        <section class="card p-5 sm:p-7"><div class="mb-5"><h2 class="text-lg font-black">Encabezado del movimiento</h2><p class="text-sm text-ink-600">Después de aplicarlo no podrá editarse ni borrarse; cualquier corrección requerirá otro movimiento.</p></div><div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><div><label class="form-label" for="type">Tipo *</label><select class="form-input" id="type" name="type" required>@foreach($types as $type)@continue($type->requiresAdjustmentPermission() && !auth()->user()->canAdjustInventory())<option value="{{ $type->value }}" @selected(old('type', $inventoryDocument->type?->value ?? \App\InventoryDocumentType::Receipt->value) === $type->value)>{{ $type->label() }}</option>@endforeach</select></div><div><label class="form-label" for="warehouse_id">Bodega *</label><select class="form-input" id="warehouse_id" name="warehouse_id" required>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(old('warehouse_id', $inventoryDocument->warehouse_id ?? $warehouses->firstWhere('is_default', true)?->id) === $warehouse->id)>{{ $warehouse->name }} · {{ $warehouse->code }}</option>@endforeach</select></div><div><label class="form-label" for="occurred_on">Fecha *</label><input class="form-input" id="occurred_on" name="occurred_on" type="date" max="{{ now()->toDateString() }}" required value="{{ old('occurred_on', $inventoryDocument->occurred_on?->toDateString() ?? now()->toDateString()) }}"></div><div><label class="form-label" for="supplier_id">Proveedor</label><select class="form-input" id="supplier_id" name="supplier_id"><option value="">Sin proveedor</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id', $inventoryDocument->supplier_id) === $supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div><div><label class="form-label" for="external_reference">Factura o referencia externa</label><input class="form-input" id="external_reference" name="external_reference" maxlength="120" value="{{ old('external_reference', $inventoryDocument->external_reference) }}"></div><div class="sm:col-span-2 xl:col-span-3"><label class="form-label" for="notes">Motivo o notas</label><textarea class="form-input min-h-24" id="notes" name="notes" maxlength="2000" placeholder="Especialmente importante para ajustes manuales">{{ old('notes', $inventoryDocument->notes) }}</textarea></div></div></section>
        <div class="flex justify-end gap-3"><a class="btn-secondary" href="{{ $editing ? route('inventory-documents.show', $inventoryDocument) : route('inventory-documents.index') }}">Cancelar</a><button class="btn-primary">{{ $editing ? 'Guardar encabezado' : 'Crear borrador y agregar productos' }}</button></div>
    </form>
@endsection
