@extends('layouts.app')

@section('title', 'Entradas y ajustes')
@section('page-title', 'Entradas y ajustes')
@section('page-subtitle', 'Documentos controlados que modifican la existencia física.')
@section('header-actions')<a href="{{ route('inventory-documents.create') }}" class="btn-primary">＋ Nuevo movimiento</a>@endsection

@section('content')
    <div class="space-y-6">
        <nav class="flex flex-wrap gap-2 text-sm"><a class="btn-secondary" href="{{ route('inventory.index') }}">Existencias</a><a class="btn-secondary border-leaf-600 text-leaf-700" href="{{ route('inventory-documents.index') }}">Entradas y ajustes</a><a class="btn-secondary" href="{{ route('inventory-counts.index') }}">Conteos</a><a class="btn-secondary" href="{{ route('inventory-movements.index') }}">Bitácora</a></nav>
        <section class="card p-5"><form method="GET" class="grid gap-4 lg:grid-cols-5"><div><label class="form-label">Buscar</label><input class="form-input" name="search" value="{{ $search }}" placeholder="Número, referencia o proveedor"></div><div><label class="form-label">Bodega</label><select class="form-input" name="warehouse_id"><option value="">Todas</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(request('warehouse_id') === $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></div><div><label class="form-label">Tipo</label><select class="form-input" name="type"><option value="">Todos</option>@foreach($types as $type)@continue($type->requiresAdjustmentPermission() && !auth()->user()->canAdjustInventory())<option value="{{ $type->value }}" @selected($selectedType === $type->value)>{{ $type->label() }}</option>@endforeach</select></div><div><label class="form-label">Estado</label><select class="form-input" name="status"><option value="">Todos</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="flex items-end gap-2"><button class="btn-primary flex-1">Filtrar</button><a class="btn-secondary" href="{{ route('inventory-documents.index') }}">Limpiar</a></div></form></section>
        <section class="card overflow-hidden">@if($documents->isEmpty())<div class="p-6"><x-empty-state title="Sin movimientos" description="Registra inventario inicial, una recepción de proveedor o un ajuste autorizado."><x-slot:action><a class="btn-primary" href="{{ route('inventory-documents.create') }}">Crear movimiento</a></x-slot:action></x-empty-state></div>@else<div class="overflow-x-auto"><table class="w-full min-w-[900px]"><thead class="bg-stone-50"><tr><th class="table-heading">Documento</th><th class="table-heading">Tipo</th><th class="table-heading">Bodega</th><th class="table-heading">Proveedor / referencia</th><th class="table-heading text-right">Líneas</th><th class="table-heading">Estado</th></tr></thead><tbody>@foreach($documents as $document)<tr><td class="table-cell"><a class="font-bold text-leaf-700 hover:underline" href="{{ route('inventory-documents.show', $document) }}">{{ $document->document_number }}</a><p class="text-xs text-ink-600">{{ $document->occurred_on->format('d/m/Y') }} · {{ $document->creator->name }}</p></td><td class="table-cell font-semibold">{{ $document->type->label() }}</td><td class="table-cell">{{ $document->warehouse->name }}</td><td class="table-cell"><p>{{ $document->supplier?->name ?: 'Sin proveedor' }}</p><p class="text-xs text-ink-600">{{ $document->external_reference ?: 'Sin referencia externa' }}</p></td><td class="table-cell text-right font-bold">{{ $document->items_count }}</td><td class="table-cell"><x-inventory-status-badge :status="$document->status" /></td></tr>@endforeach</tbody></table></div><div class="border-t border-stone-100 px-5 py-4">{{ $documents->links() }}</div>@endif</section>
    </div>
@endsection
