@extends('layouts.app')

@section('title', $document->document_number)
@section('page-title', $document->document_number)
@section('page-subtitle', $document->type->label().' · '.$document->warehouse->name)
@section('header-actions')<a href="{{ route('inventory-documents.index') }}" class="btn-secondary">Volver</a>@endsection

@section('content')
    <div class="space-y-6">
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Estado</p><div class="mt-3"><x-inventory-status-badge :status="$document->status" /></div>@if($document->posted_at)<p class="mt-2 text-xs text-ink-600">Aplicado {{ $document->posted_at->format('d/m/Y H:i') }}</p>@endif</article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Movimiento</p><p class="mt-2 font-bold">{{ $document->type->label() }}</p><p class="text-xs text-ink-600">{{ $document->type->onHandSign() > 0 ? 'Aumenta' : 'Disminuye' }} existencia física</p></article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Bodega</p><p class="mt-2 font-bold">{{ $document->warehouse->name }}</p><p class="text-xs text-ink-600">{{ $document->warehouse->code }}</p></article><article class="card p-5"><p class="text-xs font-semibold uppercase text-ink-600">Fecha</p><p class="mt-2 text-2xl font-black">{{ $document->occurred_on->format('d/m/Y') }}</p><p class="text-xs text-ink-600">{{ $document->items->count() }} líneas</p></article></section>

        @if($document->status === \App\InventoryDocumentStatus::Cancelled)<section class="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><p class="font-bold">Movimiento cancelado</p><p class="mt-1 whitespace-pre-line text-sm">{{ $document->cancellation_reason }}</p></section>@endif

        @if($canUpdate)
            <section class="card p-5 sm:p-7"><div class="mb-5"><p class="text-xs font-semibold uppercase tracking-[0.14em] text-leaf-700">Agregar línea</p><h2 class="mt-1 text-lg font-black">Producto y presentación</h2><p class="text-sm text-ink-600">La cantidad se convierte a la unidad base. Lote y vencimiento serán obligatorios si el producto así lo exige.</p></div>
                <form method="POST" action="{{ route('inventory-documents.items.store', $document) }}" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@csrf
                    <div class="sm:col-span-2"><label class="form-label" for="product_presentation_id">Producto y presentación *</label><select class="form-input" id="product_presentation_id" name="product_presentation_id" required><option value="">Selecciona…</option>@foreach($products as $product)<optgroup label="{{ $product->name }} · {{ $product->sku }}{{ $product->tracks_lots ? ' · lote' : '' }}{{ $product->tracks_expiration ? ' · vencimiento' : '' }}">@foreach($product->presentations as $presentation)<option value="{{ $presentation->id }}" @selected(old('product_presentation_id') === $presentation->id)>{{ $presentation->name }} · 1 = {{ rtrim(rtrim($presentation->conversion_factor, '0'), '.') }} {{ $product->baseUnit->symbol }}</option>@endforeach</optgroup>@endforeach</select></div>
                    <div><label class="form-label" for="quantity">Cantidad *</label><input class="form-input" id="quantity" name="quantity" type="number" min="0.000001" step="0.000001" required value="{{ old('quantity', 1) }}"></div>
                    <div><label class="form-label" for="unit_cost">Costo unitario</label><input class="form-input" id="unit_cost" name="unit_cost" type="number" min="0" step="0.0001" value="{{ old('unit_cost') }}"></div>
                    <div><label class="form-label" for="lot_number">Lote</label><input class="form-input" id="lot_number" name="lot_number" maxlength="100" value="{{ old('lot_number') }}"></div>
                    <div><label class="form-label" for="expiration_date">Vencimiento</label><input class="form-input" id="expiration_date" name="expiration_date" type="date" value="{{ old('expiration_date') }}"></div>
                    <div class="sm:col-span-2"><label class="form-label" for="item_notes">Notas de la línea</label><input class="form-input" id="item_notes" name="notes" maxlength="1000" value="{{ old('notes') }}"></div>
                    <div class="sm:col-span-2 xl:col-span-4 flex justify-end"><button class="btn-primary">Agregar producto</button></div>
                </form>
            </section>
        @endif

        <section class="card overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-stone-100 px-5 py-4"><div><h2 class="font-bold">Productos del movimiento</h2><p class="text-sm text-ink-600">Instantáneas de presentación, conversión, lote y costo.</p></div>@if($canUpdate)<a class="btn-secondary" href="{{ route('inventory-documents.edit', $document) }}">Editar encabezado</a>@endif</div>
            @if($document->items->isEmpty())<div class="p-6"><x-empty-state title="Sin productos" description="Agrega al menos una línea antes de aplicar el movimiento." /></div>@else<div class="divide-y divide-stone-100">
                @foreach($document->items as $item)
                    <article class="p-5"><div class="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_10rem_10rem_auto]"><div><p class="font-bold">{{ $item->product_name }}</p><p class="text-xs text-ink-600">{{ $item->product_sku }} · {{ $item->presentation_name }}</p>@if($item->lot_number)<p class="mt-1 text-xs text-ink-600">Lote {{ $item->lot_number }}@if($item->expiration_date) · vence {{ $item->expiration_date->format('d/m/Y') }}@endif</p>@endif</div><div><p class="text-xs font-semibold uppercase text-ink-600">Cantidad</p><p class="font-bold">{{ rtrim(rtrim($item->quantity, '0'), '.') }} {{ $item->presentation_name }}</p></div><div><p class="text-xs font-semibold uppercase text-ink-600">Equivalencia</p><p class="font-bold">{{ rtrim(rtrim($item->base_quantity, '0'), '.') }} {{ $item->base_unit_symbol }}</p></div>@if($canUpdate)<form method="POST" action="{{ route('inventory-documents.items.destroy', [$document, $item]) }}" data-confirm="¿Retirar esta línea?">@csrf @method('DELETE')<button class="btn-danger">Retirar</button></form>@endif</div>
                        @if($canUpdate)<details class="mt-4 rounded-xl border border-stone-200 bg-stone-50 p-4"><summary class="cursor-pointer text-sm font-semibold text-leaf-700">Editar esta línea</summary><form method="POST" action="{{ route('inventory-documents.items.update', [$document, $item]) }}" class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@csrf @method('PUT')<div class="sm:col-span-2"><label class="form-label">Presentación</label><select class="form-input" name="product_presentation_id" required>@foreach($products as $product)<optgroup label="{{ $product->name }}">@foreach($product->presentations as $presentation)<option value="{{ $presentation->id }}" @selected($presentation->id === $item->product_presentation_id)>{{ $presentation->name }}</option>@endforeach</optgroup>@endforeach</select></div><div><label class="form-label">Cantidad</label><input class="form-input" name="quantity" type="number" min="0.000001" step="0.000001" required value="{{ $item->quantity }}"></div><div><label class="form-label">Costo unitario</label><input class="form-input" name="unit_cost" type="number" min="0" step="0.0001" value="{{ $item->unit_cost }}"></div><div><label class="form-label">Lote</label><input class="form-input" name="lot_number" maxlength="100" value="{{ $item->lot_number }}"></div><div><label class="form-label">Vencimiento</label><input class="form-input" name="expiration_date" type="date" value="{{ $item->expiration_date?->toDateString() }}"></div><div class="sm:col-span-2"><label class="form-label">Notas</label><input class="form-input" name="notes" maxlength="1000" value="{{ $item->notes }}"></div><div class="sm:col-span-2 xl:col-span-4 flex justify-end"><button class="btn-primary">Guardar línea</button></div></form></details>@endif
                    </article>
                @endforeach
            </div>@endif
        </section>

        <div class="grid items-start gap-6 lg:grid-cols-2">
            <section class="card p-5"><h2 class="font-bold">Información y auditoría</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-xs font-semibold uppercase text-ink-600">Proveedor</dt><dd>{{ $document->supplier?->name ?: 'Sin proveedor' }}</dd></div><div><dt class="text-xs font-semibold uppercase text-ink-600">Referencia externa</dt><dd>{{ $document->external_reference ?: 'Sin referencia' }}</dd></div><div><dt class="text-xs font-semibold uppercase text-ink-600">Creado por</dt><dd>{{ $document->creator->name }} · {{ $document->created_at->format('d/m/Y H:i') }}</dd></div>@if($document->postedBy)<div><dt class="text-xs font-semibold uppercase text-ink-600">Aplicado por</dt><dd>{{ $document->postedBy->name }} · {{ $document->posted_at->format('d/m/Y H:i') }}</dd></div>@endif @if($document->notes)<div><dt class="text-xs font-semibold uppercase text-ink-600">Notas</dt><dd class="whitespace-pre-line">{{ $document->notes }}</dd></div>@endif</dl></section>
            @if($canUpdate)<section class="card p-5"><h2 class="font-bold">Cerrar el borrador</h2><p class="mt-2 text-sm leading-6 text-ink-600">Aplicar modifica la existencia de forma permanente. Si es una salida, se rechazará completa cuando alguna línea no tenga existencia física suficiente.</p><form method="POST" action="{{ route('inventory-documents.post', $document) }}" class="mt-4" data-confirm="¿Aplicar este movimiento? Después no podrá editarse.">@csrf<button class="btn-primary w-full" @disabled($document->items->isEmpty())>Aplicar movimiento</button></form><form method="POST" action="{{ route('inventory-documents.cancel', $document) }}" class="mt-5 space-y-3" data-confirm="¿Cancelar este borrador?">@csrf<label class="form-label" for="reason">Motivo de cancelación *</label><textarea class="form-input min-h-20" id="reason" name="reason" required maxlength="1000"></textarea><button class="btn-danger w-full">Cancelar borrador</button></form></section>@endif
        </div>
    </div>
@endsection
